from django.urls import path
from myapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('aec_main/',views.aec_main,name = 'aec-main'),
    path('',views.login_page,name = 'login-page'),
    path('login/', views.login_view, name="login"),
    path('latlong_json/', views.latlong_json, name='latlong_json'),
    path('aec_register/', views.aec_register, name='aec-register'),
    path('encode_password/', views.encode_password,name="encode-password"),
    path('reset_password/',views.reset_password,name="reset_password"),
    # path('loginprocess/',views.loginprocess,name="loginprocess"),
    path('aec_modal/',views.aec_modal,name="aec_modal"),
    path('aec_otp/<str:pk>',views.aec_otp,name="aec_otp"), 
    path('aec_sweetalarm/',views.aec_sweetalarm,name="aec_sweetalarm"),
    path('aec_erroralerm/',views.aec_erroralerm,name="aec_erroralerm"),
    path('resend_otp/<str:pk>',views.resend_otp,name="resend_otp"),
    path('aec_regerror/',views.aec_regerror,name="aec_regerror"),  
    path('logout_request/',views.logout_request,name="logout-request"),
    path('country_databases/',views.country_databases,name="country_databases"),
    path('get_states/',views.get_states,name="get-states"),
    path('get_districts/',views.get_districts,name="get-districts"),
    path('aec_masterscreen/',views.aec_masterscreen,name="aec_masterscreen"),
    path('state_databases/',views.state_databases,name="state_databases"),
    path('district_databases/',views.district_databases,name="district_databases"),
    # path('add_countrydata/',views.add_countrydata,name="add_countrydata"),
    # path('delete_countrydata/',views.delete_countrydata,name="delete_countrydata"),
    path('aec_masterdata/',views.aec_masterdata,name="aec_masterdata"),
    path('aec_localbodydata/',views.aec_localbodydata,name="aec_localbodydata"),
    path('aec_talukdata/',views.aec_talukdata,name="aec_talukdata"),
    path('aec_villagedata/',views.aec_villagedata,name="aec_villagedata"),
    path('add_field/',views.add_field,name="add_field"),
    path('add_statefield/',views.add_statefield,name="add_statefield"),
    path('add_districtfield/',views.add_districtfield,name="add_districtfield"),
    path('delete_item/<country_id>/', views.delete_item, name='delete_item'),
    path('delete_stateitem/<state_id>/',views.delete_stateitem,name="delete_stateitem"), 
    path('delete_districtitem/<district_id>/',views.delete_districtitem,name="delete_districtitem"),
    path('delete_masteritem/<master_id>/',views.delete_masteritem,name="delete_masteritem"),
    path('delete_localbodyitem/<localbody_id>/',views.delete_localbodyitem,name="delete_localbodyitem"),
    path('delete_talukitem/<taluk_id>/',views.delete_talukitem,name="delete_talukitem"),
    path('delete_villageitem/<village_id>/',views.delete_villageitem,name="delete_villageitem"),
    path('add_masterfield/',views.add_masterfield,name="add_masterfield"),
    path('add_localbodyfield/',views.add_localbodyfield,name="add_localbodyfield"),
    path('add_talukfields/',views.add_talukfields,name="add_talukfields"),
    path('add_villagefields/',views.add_villagefields,name="add_villagefields"),
    # path('aec_data/',views.aec_data,name="aec_data"),
    path('edit_country/<int:country_id>/', views.edit_country, name='edit_country'),
    path('edit_district/<int:district_id/',views.edit_district,name="edit_district"),
    path('edit_state/<int:state_id>/',views.edit_state,name="edit_state"),
    path('edit_village/<int:village_id>',views.edit_village,name="edit_village"),
    path('edit_district/<int:district_id>/',views.edit_district,name="edit_district"),
    path('edit_master/<int:masterplan_id>/',views.edit_master,name="edit_master"),
    path('edit_localbody/<int:localbody_id>/',views.edit_localbody,name="edit_localbody"),
    path('edit_village/<int:village_id>/',views.edit_village,name="edit_village"),
    path('edit_taluk/<int:taluk_id>/',views.edit_taluk,name="edit_taluk"),
    # path('show_districts/',views.show_districts,name="show_districts"),
    path('get_district/', views.get_district, name='get_district'), 
    path('get_masterplan/<int:district_id>/', views.get_masterplan, name='get_masterplan'),
    path('aec_villagesurverylist/',views.aec_villagesurverylist,name="aec_villagesurverylist"),
    path('aec_landusedata/',views.aec_landusedata,name="aec_landusedata"),
    path('add_landusedata/',views.add_landusedata,name="add_landusedata"),
    path('delete_landuse/<landuse_id>/',views.delete_landuse,name="delete_landuse"),
    path('edit_landusedata/<int:landuse_id>/',views.edit_landusedata,name="edit_landusedata"),
    path('delete_villagesurvery/<villagesurvery_id>/',views.delete_villagesurvery,name="delete_villagesurvery"),
    path('add_villagesurvery/',views.add_villagesurvery,name="add_villagesurvery"),
    path('edit_villagesurvery/<int:villagesurvey_id>/',views.edit_villagesurvery,name="edit_villagesurvery"),
    path('delete_villagesurvey/<villagesurvey_id>/',views.delete_villagesurvey,name="delete_villagesurvey"),
    path('aec_townlist/',views.aec_townlist,name="aec_townlist"),
    path('add_townlist/',views.add_townlist,name="add_townlist"),
    path('edit_townlist/<int:townlist_id>/',views.edit_townlist,name="edit_townlist"),
    path('delete_townlist/<townlist_id>/',views.delete_townlist,name="delete_townlist"),
]

    


