# Generated by Django 3.2.13 on 2023-10-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20231025_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='townlist',
            unique_together={('wardno', 'blockno', 'surveyno_from', 'localbody_id', 'landuse_detail')},
        ),
    ]
