# Generated by Django 3.2.13 on 2023-10-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_townlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='townlist',
            name='localbody_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.localbody'),
        ),
        migrations.AlterField(
            model_name='townlist',
            name='localbody_id',
            field=models.IntegerField(),
        ),
    ]
