# Generated by Django 3.2.13 on 2023-10-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_townlist_townlist_townlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuse',
            name='landuse_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
