# Generated by Django 3.2.13 on 2023-10-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_landuse_landuse_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='townlist',
            unique_together=set(),
        ),
    ]
